### ISSUE TITLE
Virus total detects a virus

### ISSUE THREAD

**Issue by eni9mv** [ALittlePatate/Rainbow-Cheat-CS-GO#1]
when i try to  compile and scarning it on VirusTotal its gave me 7/71 viruses 
and when i scan u release it gave me 0/71 viruses 

can u tell me why or what u did to get Fully Undetectable 😃 ?

**Comment by ALittlePatate** [comment]
When we are talking about undetectable, we talk about VAC (Valve Anti Cheat). So it's fully undetectable by VAC. Yet it's also not detectable by any kind of anti viruses because it's not using any sort of "virus behavior" to be undetectable by VAC. Virus Total are sometimes giving false positive. If you don't trust me, the source code is here, check it!
