### ISSUE TITLE
error on pip 

### ISSUE THREAD

**Issue by eni9mv** [ALittlePatate/Rainbow-Cheat-CS-GO#3]
hi when i try to run this command pip install -r requirements.txt on CMD i got this message:
You are using pip version 7.1.2, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by eni9mv** [comment]
when i try to upgrade it 
it said 'python' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ALittlePatate** [comment]
this isn't an error actually, it's just telling you that you should update it. But whatever, if you want to update pip, use "install --upgrade pip" command. And if your cmd is saying "it said 'python' is not recognized as an internal or external command,operable program or batch file." then it's because python is not added to PATH
